apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  selector:
    matchLabels:
      run: redis
  replicas: 1
  template:
    metadata:
      labels:
        run: redis
    spec:
      containers:
      - name: redis
        image: sneyd321/redis
        ports:
        - containerPort: 6379

    
        
      imagePullSecrets:
        - name: key